### ISSUE TITLE
Enum 类型 能支持存储成String吗

### ISSUE THREAD

**Issue by zhaozhengyan** [SkyChenSky/Sikiro.Dapper.Extension#10]
Enum 类型 能支持存储成String吗

**Comment by SkyChenSky** [comment]
你这个问题的本质我认为属于一种规范问题，估计你们公司约定是在数据库记录枚举标识，应该考虑到可读性，然而业界存储更多是选择记录枚举值，1占用空间少，2效率高，虽然这个并非作为一个决定性的理由，但是框架的设计也需要迎合使用占比高的。
其实你这个问题可以换一种使用方式，你可以修改enum类型的属性为string类型，Sex = ESex.Max.Tostring()，因为你们数据库类型应该是varchar，那么varchar、char理应与string匹配映射。

**Comment by SkyChenSky** [comment]
另外还有个方法，就是自己去实现一个EnumAttribute，通过传参判断是否记录枚举值还是枚举标识，当然这个是需要花点时间改改源码

**Comment by zhaozhengyan** [comment]
好的，了解
