### ISSUE TITLE
访问成员没有带引用符号，如果遇上关键词会报错

### ISSUE THREAD

**Issue by holdengong** [SkyChenSky/Sikiro.Dapper.Extension#5]
访问成员没有带引用符号，如果遇上关键词会报错，VisitMemember方法

**Comment by SkyChenSky** [comment]
对，是加上中括号吧？

**Comment by holdengong** [comment]
是的，sqlserver是中括号，Mysql是`.. 
https://github.com/tmsmith/Dapper-Extensions 这个库有数据库方言的处理
可以参考

**Comment by SkyChenSky** [comment]
谢谢你的建议，2.0.0版本已经完成了，添加了对msql支持，和异步方法，方言问题也解决了。欢迎试用
