### ISSUE TITLE
Suggestion to add async methods

### ISSUE THREAD

**Issue by brunotourinho** [SkyChenSky/Sikiro.Dapper.Extension#7]
Hey! Nice Work! 
My suggestion is implement the async methods like InsertAsync, DeleteAsync, etc.

**Comment by SkyChenSky** [comment]
Good advice, I have plans to write, but recently there are more things in the company. Do you have any interest in contributing code

**Comment by brunotourinho** [comment]
I'm sorry, but I don't have much time either.

**Comment by SkyChenSky** [comment]
V2.0.0 is done. Suport mysql and  async function.Welcome to use
